/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ScientificCalculator;

/**
 *
 * @author swati
 */
public class ScientificCalculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public ScientificCalculator() {
        initComponents();
        jRadioButton1.setEnabled(false);
    }
    double num1, num2, result;
    String opr;
    
    public void enable() {
        jTextField1.setEnabled(true);
        
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(true);
        
        jButton43.setEnabled(true);
        jButton44.setEnabled(true);
        jButton45.setEnabled(true);
        jButton46.setEnabled(true);
        jButton47.setEnabled(true);
        jButton48.setEnabled(true);
        jButton49.setEnabled(true);
        jButton50.setEnabled(true);
        jButton51.setEnabled(true);
        jButton52.setEnabled(true);
        jButton53.setEnabled(true);
        jButton54.setEnabled(true);
        jButton55.setEnabled(true);
        jButton56.setEnabled(true);
        jButton57.setEnabled(true);
        jButton58.setEnabled(true);
        jButton59.setEnabled(true);
        jButton60.setEnabled(true);
        jButton61.setEnabled(true);
        jButton62.setEnabled(true);
        jButton63.setEnabled(true);
        jButton64.setEnabled(true);
        jButton65.setEnabled(true);
        jButton66.setEnabled(true);
        jButton67.setEnabled(true);
        jButton68.setEnabled(true);
        jButton71.setEnabled(true);
        jButton72.setEnabled(true);
        jButton73.setEnabled(true);
        jButton74.setEnabled(true);
        jButton75.setEnabled(true);
        jButton76.setEnabled(true);
        jButton77.setEnabled(true);
    }
    
    public void disable() {
        jTextField1.setEnabled(false);
        
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(false);
        
        jButton43.setEnabled(false);
        jButton44.setEnabled(false);
        jButton45.setEnabled(false);
        jButton46.setEnabled(false);
        jButton47.setEnabled(false);
        jButton48.setEnabled(false);
        jButton49.setEnabled(false);
        jButton50.setEnabled(false);
        jButton51.setEnabled(false);
        jButton52.setEnabled(false);
        jButton53.setEnabled(false);
        jButton54.setEnabled(false);
        jButton55.setEnabled(false);
        jButton56.setEnabled(false);
        jButton57.setEnabled(false);
        jButton58.setEnabled(false);
        jButton59.setEnabled(false);
        jButton60.setEnabled(false);
        jButton61.setEnabled(false);
        jButton62.setEnabled(false);
        jButton63.setEnabled(false);
        jButton64.setEnabled(false);
        jButton65.setEnabled(false);
        jButton66.setEnabled(false);
        jButton67.setEnabled(false);
        jButton68.setEnabled(false);
        jButton71.setEnabled(false);
        jButton72.setEnabled(false);
        jButton73.setEnabled(false);
        jButton74.setEnabled(false);
        jButton75.setEnabled(false);
        jButton76.setEnabled(false);
        jButton77.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCIENTIFIC CALCULATOR");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(355, 522));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 20, 324, 52));

        jRadioButton1.setBackground(new java.awt.Color(255, 51, 51));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 78, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 51, 51));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 78, -1, -1));

        jButton43.setBackground(new java.awt.Color(204, 204, 204));
        jButton43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton43.setForeground(new java.awt.Color(0, 0, 0));
        jButton43.setText("sqrt");
        jButton43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton43.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton43.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton43.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 121, -1, -1));

        jButton44.setBackground(new java.awt.Color(204, 204, 204));
        jButton44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton44.setForeground(new java.awt.Color(0, 0, 0));
        jButton44.setText("x^y");
        jButton44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton44.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton44.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton44.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 223, -1, -1));

        jButton45.setBackground(new java.awt.Color(204, 204, 204));
        jButton45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton45.setForeground(new java.awt.Color(0, 0, 0));
        jButton45.setText("1/x");
        jButton45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton45.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton45.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton45.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 172, -1, -1));

        jButton46.setBackground(new java.awt.Color(204, 204, 204));
        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton46.setForeground(new java.awt.Color(0, 0, 0));
        jButton46.setText("x^3");
        jButton46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton46.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton46.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton46.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 274, -1, -1));

        jButton47.setBackground(new java.awt.Color(204, 204, 204));
        jButton47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton47.setForeground(new java.awt.Color(0, 0, 0));
        jButton47.setText("n!");
        jButton47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton47.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton47.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton47.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 376, -1, -1));

        jButton48.setBackground(new java.awt.Color(204, 204, 204));
        jButton48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton48.setForeground(new java.awt.Color(0, 0, 0));
        jButton48.setText("x^2");
        jButton48.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton48.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton48.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton48.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 325, -1, -1));

        jButton49.setBackground(new java.awt.Color(204, 204, 204));
        jButton49.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton49.setForeground(new java.awt.Color(0, 0, 0));
        jButton49.setText("+/-");
        jButton49.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton49.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton49.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton49.setPreferredSize(new java.awt.Dimension(60, 45));
        getContentPane().add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 427, -1, -1));

        jButton50.setBackground(new java.awt.Color(204, 204, 204));
        jButton50.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton50.setForeground(new java.awt.Color(0, 0, 0));
        jButton50.setText("exp");
        jButton50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton50.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton50.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton50.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 121, -1, -1));

        jButton51.setBackground(new java.awt.Color(204, 204, 204));
        jButton51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton51.setForeground(new java.awt.Color(0, 0, 0));
        jButton51.setText("%");
        jButton51.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton51.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton51.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton51.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 223, -1, -1));

        jButton52.setBackground(new java.awt.Color(204, 204, 204));
        jButton52.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton52.setForeground(new java.awt.Color(0, 0, 0));
        jButton52.setText("log");
        jButton52.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton52.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton52.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton52.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 172, -1, -1));

        jButton53.setBackground(new java.awt.Color(153, 153, 153));
        jButton53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton53.setForeground(new java.awt.Color(0, 0, 0));
        jButton53.setText("7");
        jButton53.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton53.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton53.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton53.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 274, -1, -1));

        jButton54.setBackground(new java.awt.Color(153, 153, 153));
        jButton54.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton54.setForeground(new java.awt.Color(0, 0, 0));
        jButton54.setText("1");
        jButton54.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton54.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton54.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton54.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 376, -1, -1));

        jButton55.setBackground(new java.awt.Color(153, 153, 153));
        jButton55.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton55.setForeground(new java.awt.Color(0, 0, 0));
        jButton55.setText("4");
        jButton55.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton55.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton55.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton55.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 325, -1, -1));

        jButton56.setBackground(new java.awt.Color(153, 153, 153));
        jButton56.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton56.setForeground(new java.awt.Color(0, 0, 0));
        jButton56.setText("0");
        jButton56.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton56.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton56.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton56.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 427, -1, -1));

        jButton57.setBackground(new java.awt.Color(204, 204, 204));
        jButton57.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton57.setForeground(new java.awt.Color(0, 0, 0));
        jButton57.setText("sin");
        jButton57.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton57.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton57.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton57.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 121, -1, -1));

        jButton58.setBackground(new java.awt.Color(255, 102, 0));
        jButton58.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton58.setForeground(new java.awt.Color(0, 0, 0));
        jButton58.setText("Clr");
        jButton58.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton58.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton58.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton58.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 223, -1, -1));

        jButton59.setBackground(new java.awt.Color(204, 204, 204));
        jButton59.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton59.setForeground(new java.awt.Color(0, 0, 0));
        jButton59.setText("sinh");
        jButton59.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton59.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton59.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton59.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 172, -1, -1));

        jButton60.setBackground(new java.awt.Color(153, 153, 153));
        jButton60.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton60.setForeground(new java.awt.Color(0, 0, 0));
        jButton60.setText("8");
        jButton60.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton60.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton60.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton60.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 274, -1, -1));

        jButton61.setBackground(new java.awt.Color(153, 153, 153));
        jButton61.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton61.setForeground(new java.awt.Color(0, 0, 0));
        jButton61.setText("2");
        jButton61.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton61.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton61.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton61.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 376, -1, -1));

        jButton62.setBackground(new java.awt.Color(153, 153, 153));
        jButton62.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton62.setForeground(new java.awt.Color(0, 0, 0));
        jButton62.setText("5");
        jButton62.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton62.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton62.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton62.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 325, -1, -1));

        jButton63.setBackground(new java.awt.Color(204, 204, 204));
        jButton63.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton63.setForeground(new java.awt.Color(0, 0, 0));
        jButton63.setText(".");
        jButton63.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton63.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton63.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton63.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 427, -1, -1));

        jButton64.setBackground(new java.awt.Color(204, 204, 204));
        jButton64.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton64.setForeground(new java.awt.Color(0, 0, 0));
        jButton64.setText("cos");
        jButton64.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton64.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton64.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton64.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 121, -1, -1));

        jButton65.setBackground(new java.awt.Color(255, 102, 0));
        jButton65.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton65.setForeground(new java.awt.Color(0, 0, 0));
        jButton65.setText("B");
        jButton65.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton65.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton65.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton65.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 223, -1, -1));

        jButton66.setBackground(new java.awt.Color(204, 204, 204));
        jButton66.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton66.setForeground(new java.awt.Color(0, 0, 0));
        jButton66.setText("cosh");
        jButton66.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton66.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton66.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton66.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton66ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 172, -1, -1));

        jButton67.setBackground(new java.awt.Color(153, 153, 153));
        jButton67.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton67.setForeground(new java.awt.Color(0, 0, 0));
        jButton67.setText("9");
        jButton67.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton67.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton67.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton67.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 274, -1, -1));

        jButton68.setBackground(new java.awt.Color(153, 153, 153));
        jButton68.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton68.setForeground(new java.awt.Color(0, 0, 0));
        jButton68.setText("3");
        jButton68.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton68.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton68.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton68.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton68ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 376, -1, -1));

        jButton69.setBackground(new java.awt.Color(153, 153, 153));
        jButton69.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton69.setForeground(new java.awt.Color(0, 0, 0));
        jButton69.setText("6");
        jButton69.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton69.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton69.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton69.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 325, -1, -1));

        jButton71.setBackground(new java.awt.Color(204, 204, 204));
        jButton71.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton71.setForeground(new java.awt.Color(0, 0, 0));
        jButton71.setText("tan");
        jButton71.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton71.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton71.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton71.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton71ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 121, -1, -1));

        jButton72.setBackground(new java.awt.Color(204, 204, 204));
        jButton72.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton72.setForeground(new java.awt.Color(0, 0, 0));
        jButton72.setText("+");
        jButton72.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton72.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton72.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton72.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton72ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 223, -1, -1));

        jButton73.setBackground(new java.awt.Color(204, 204, 204));
        jButton73.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton73.setForeground(new java.awt.Color(0, 0, 0));
        jButton73.setText("tanh");
        jButton73.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton73.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton73.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton73.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton73ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 172, -1, -1));

        jButton74.setBackground(new java.awt.Color(204, 204, 204));
        jButton74.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton74.setForeground(new java.awt.Color(0, 0, 0));
        jButton74.setText("-");
        jButton74.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton74.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton74.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton74.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton74ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 274, -1, -1));

        jButton75.setBackground(new java.awt.Color(204, 204, 204));
        jButton75.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton75.setForeground(new java.awt.Color(0, 0, 0));
        jButton75.setText("/");
        jButton75.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton75.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton75.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton75.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton75ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 376, -1, -1));

        jButton76.setBackground(new java.awt.Color(204, 204, 204));
        jButton76.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton76.setForeground(new java.awt.Color(0, 0, 0));
        jButton76.setText("*");
        jButton76.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jButton76.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton76.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton76.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton76ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 325, -1, -1));

        jButton77.setBackground(new java.awt.Color(255, 102, 0));
        jButton77.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton77.setForeground(new java.awt.Color(0, 0, 0));
        jButton77.setText("=");
        jButton77.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton77.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton77.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton77.setPreferredSize(new java.awt.Dimension(60, 45));
        jButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton77ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 427, 126, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\swati\\OneDrive\\Desktop\\wp11180956-orange-and-black-4k-wallpapers.jpg")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 3, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
        jTextField1.setText(jTextField1.getText()+"0");
    }//GEN-LAST:event_jButton56ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        jTextField1.setText(jTextField1.getText()+"1");
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        jTextField1.setText(jTextField1.getText()+"2");
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton68ActionPerformed
        jTextField1.setText(jTextField1.getText()+"3");
    }//GEN-LAST:event_jButton68ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        jTextField1.setText(jTextField1.getText()+"4");
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        jTextField1.setText(jTextField1.getText()+"5");
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        jTextField1.setText(jTextField1.getText()+"6");
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        jTextField1.setText(jTextField1.getText()+"7");
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        jTextField1.setText(jTextField1.getText()+"8");
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        jTextField1.setText(jTextField1.getText()+"9");
    }//GEN-LAST:event_jButton67ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        jTextField1.setText(jTextField1.getText()+".");
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        jTextField1.setText("");
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        String backSpace=null;
        
        if(jTextField1.getText().length() > 0) {
            StringBuilder s=new StringBuilder(jTextField1.getText());
            s.deleteCharAt(jTextField1.getText().length()-1);
            backSpace=s.toString();
            jTextField1.setText(backSpace);
        }
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton72ActionPerformed
        // num1, num2 declared globally
        num1=Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr="+";
    }//GEN-LAST:event_jButton72ActionPerformed

    private void jButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton74ActionPerformed
        // num1, num2 declared globally
        num1=Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr="-";
    }//GEN-LAST:event_jButton74ActionPerformed

    private void jButton76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton76ActionPerformed
        // num1, num2 declared globally
        num1=Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr="*";
    }//GEN-LAST:event_jButton76ActionPerformed

    private void jButton75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton75ActionPerformed
        // num1, num2 declared globally
        num1=Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr="/";
    }//GEN-LAST:event_jButton75ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // num1, num2 declared globally
        num1=Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr="%";
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton77ActionPerformed
        num2=Double.parseDouble(jTextField1.getText());
        
        if(opr=="+") {
            result=num1+num2;
            jTextField1.setText(Double.toString(result));
        } else if(opr=="-") {
            result=num1-num2;
            jTextField1.setText(Double.toString(result));
        } else if(opr=="*") {
            result=num1*num2;
            jTextField1.setText(Double.toString(result));
        } else if(opr=="/") {
            result=num1/num2;
            jTextField1.setText(Double.toString(result));
        } else if(opr=="%") {
            result=num1%num2;
            jTextField1.setText(Double.toString(result));
        } else if(opr=="x^y") {
            result=num1;
            for(int i=0;i<num2-1;i++) {
                result=result*num1;
            }
            jTextField1.setText(Double.toString(result));
        }
    }//GEN-LAST:event_jButton77ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        double t=Math.sin(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        double t=Math.cos(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        double t=Math.tan(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton71ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        double t=Math.sinh(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton66ActionPerformed
        double t=Math.cosh(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton66ActionPerformed

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
        double t=Math.tanh(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton73ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        double t=Math.log(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        double t=Math.exp(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        double t=Math.sqrt(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        double t=1/(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        Double t=Double.parseDouble(jTextField1.getText());
        
        t=t*t;
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        Double t=Double.parseDouble(jTextField1.getText());
        
        t=t*t*t;
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+t);
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        num1=Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText("");
        opr="x^y";
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        Double t=Double.parseDouble(jTextField1.getText());
        result=1;
        while(t>0) {
            result=result*t;
            t--;
        }
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText()+result);
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        enable();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        disable();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
